server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

wechat:
  config:
    originalId: gh_60da19b9a6c8
    token: x9x6
    app-id: wxc18b4767329f4e29
    appsecret: 1e7dfd1461e48d519794c01f559eacf1
    template-id: dj2MupGuE_aBVACvYlJtFPxc2i7TziDHqycAyUqqIvY

spring:
  datasource:
    username: root
    password: 123456
    # mysql的话，本地是3306，docker映射的是13306，改配置别忘了设置
    url: jdbc:mysql://127.0.0.1:13306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000143682131
  merchant_private_key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCJkvLTyhrPwlpB/MlgLL9sJvYbb9tOs53n+LgE6orp939RfMCkTCrevF2dys13VvMV9ut6HKmdDLBC2+Pa9Th8K6Lg3NuBA5MlZjiC+yPwY06dTC8uivhGUdqoLHeEFRTOTbxQjraMPDrrJGVi5aHrB1wEGwhuBWMz1eFZaoV0Ve+atOpN3qmzOyQjDx5GWZk1S2PUZJ28sqOJd38mn2DWIWKZWyLQjlgzFIE+qtkotRDBKKStjcE9jwunt9tdlLWUBuo8apXMVKHOSv2KKOoM75u3xR2pcyWFVarXvXOe1ABMkTbddPyBK0lypEQOKa/edNxMZtWTkFruf2VreuY7AgMBAAECggEALalQX2sdKwfe3TgBvqIbhtIHrWOa7qw/JNcwfLE8GhvDblBxwBZnxDXQ/KZrO8joNcoWrhkFUtL7TbWeEvaBIPV6wheL425EUI11BERG0WqklSDMKC6H6Q8R+++GW5iDp1W1wyca/8Cd7Z3O6Nw+ubtflx1B1wKCwpmiigMI+Gtw14uEAJ3zFMPLHDEsTq11WmHNSv/0P13F5jSKzAAnsY03E8Fka3kyZUMGIxkLvFY2V299m3g81LT9QHOy9VsSOlAE2RuEDSc4evmuJXs4VX/Pcj5JvwNGKJs4+NAlB7FGkI53ctuK31tLdrUlH1DHrads/oBxYvYMayz5c8+hgQKBgQC/+YUV/zp2naOlj/DdZ0ADroeMoVly+dTMZaAiSYL6HgNlefOeJFXcCDgA858Kchm1owzcRDS8+HSFeItdaDp3ZY6BtCw2SQCjMjAa3OcjhFyLJWZmaEUSJHlx8GIG0s+eOqN2mwG3K0hUSvCFsQ4SbMuNLAZoBIC+rUz9tnHw6QKBgQC3dMoygUW4p4qAvYfKzmoJbgNNlh/LlM1lW3TeIN2nAU9RMHC+PJWIVMoZ+MRD9rOdneYOhSXjcl6SvJRNRO8yWWCZAeJTXAcxtWgTvW9e9SFdYDaneAL8vHRCdbPD48NwQ/VgldV/lOVfVdRejvBpNTnlUt9YtgvyG2zp0PxHgwKBgQC27RxTiZA71ppI+I+baPcmive+mUCSvlx3J58fDM0xZ8f0ue/ZkOX/dBVpUrsJSRAWc/edK6DVMCpXxDWIG/kaLDtOfFBkqcthtkEAV94nichlDo40psaqMvdGCrhdqCMNsvJv4eQQlb2mFIJ74ep2xBRxwLGaDDBhgOEMIP0RgQKBgQCeeQCBCDJWBEQcWZyHkC8A3kt0Jg5pKa0TtSELEJDnxrXhiFqbunHhRn0eWkoP+3fE27TzLglApHcVglkJNlb5w0MyaPI81+5O/kldY/JksJOVuZr8pyrNb21uS4Zx3LnirJG2UTgP8WsCI35EAG2kNBpDAod0di1zgkVe5OxISQKBgQCjdAFKte3CN4z2Aw+QAnyQE2gNUqk06oHYBc4IRRqf0J339G3py0gWlMtjezuV5nW4uQb6BhFBMf7ZqwhfD/qPood6A8iKSvyrM+xoifjwVs+zu0h7zKe3XFAwRjwLE64hxtXQWcALQ0Q0bSjgPtkQnG9L2hZtRxyeju2BoPsgVg==
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq8O5t19LClsSORIN18Z8kORP/8Rhim0+iXXqQXCvDhPS7b1CJaxZ9Nw9zQoCgmOPI22RI5sQqr3mRrbEyNzZtp11617xrIyEx1vaz2fcsg8SE9G5QiaN4kLdv/TdT4t/CrPQxuhfRF0Ezw7eCCZC19I7FstDCsM+6y9MWrwEpSbn1md7b79/myUz8c0g9VWJLYZuTLsyy+mP8DuLp5SOic0kSY9AfPlg7zbwXSg0whTd0qgsoo0S9cmHSZFcjxgSzOGwLgr1UKIzP73YRQpYd3o1b6w94gF9PaHvksMgFxNMENCFZMe/aVAFt45olOlzVkv4VQ/YMTtvQtwxWSc0VwIDAQAB
  notify_url: http://makiatox-studio.natapp1.cc/api/v1/alipay/alipay_notify_url
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

logging:
  level:
    root: info
  config: classpath:logback-spring.xml