server:
  port: 8092
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

wechat:
  config:
    originalid: gh_60da19b9a6c8
    token: x9x6

logging:
  level:
    root: info
  config: classpath:logback-spring.xml