server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

wechat:
  config:
    originalId: gh_60da19b9a6c8
    token: x9x6
    app-id: wxc18b4767329f4e29
    appsecret: 1e7dfd1461e48d519794c01f559eacf1
    template-id: UKCpF7aEbXU1W0F0582ptzfGYrFIvh97CknxVqfgGDI

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging:
  level:
    root: info
  config: classpath:logback-spring.xml